// Optional browser acceptance check. Install Playwright locally or set PLAYWRIGHT_MODULE.
import { pathToFileURL } from 'node:url';
import { mkdir, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page=await browser.newPage({viewport:{width:1512,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const url=process.env.DEMO_URL||'http://127.0.0.1:5174/baseball-digital-twin-demo/';
await mkdir('artifacts',{recursive:true});
try {
  await page.goto(url);await page.waitForSelector('#scene canvas');await page.waitForFunction(()=>document.querySelector('#hud-type')?.textContent.includes('FF'));
  assert.equal(await page.locator('.app').getAttribute('data-plan-version'),'3.1');
  assert.equal(await page.locator('[data-stage="poc"]').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#node-list .node').count(),9);
  assert.ok((await page.locator('#stage-brief').textContent()).includes('15.3–22.0萬'));
  await page.screenshot({path:'artifacts/v3-poc.png'});
  await page.locator('[data-panel="spin"]').click();
  assert.ok((await page.locator('#spin-panel').textContent()).includes('第一期必要驗收'));
  assert.ok((await page.locator('#optics-warnings').textContent()).includes('少於8'));
  const pixels=await page.locator('#optics-results strong').first().textContent();
  await page.locator('#optics-mode').selectOption('roi');
  assert.equal(await page.locator('#optics-results strong').first().textContent(),pixels,'ROI must not magnify ball');
  await page.locator('#optics-mode').selectOption('full');
  await page.locator('#optics-focal').fill('25');
  assert.ok((await page.locator('#optics-warnings').textContent()).includes('低於80px'));
  await page.locator('#optics-focal').fill('50');
  await page.locator('#spin-focus').click();
  await page.screenshot({path:'artifacts/v3-spin.png'});
  await page.locator('#axis-toggle').click();assert.equal(await page.locator('#axis-toggle').getAttribute('aria-pressed'),'false');
  await page.locator('#axis-toggle').click();
  await page.locator('#measurement-zone').click();assert.equal(await page.locator('#measurement-zone').getAttribute('aria-pressed'),'false');
  await page.locator('#measurement-zone').click();
  await page.locator('[data-panel="nodes"]').click();
  await page.locator('#option-fpga').check();await page.locator('#option-radar60').check();
  assert.equal(await page.locator('#node-list .node').count(),11);
  assert.ok((await page.locator('#optional-note').textContent()).includes('未加進一期BOM'));
  await page.locator('#option-fpga').uncheck();await page.locator('#option-radar60').uncheck();
  await page.locator('[data-panel="plan"]').click();
  assert.ok((await page.locator('.budget-hero').first().textContent()).includes('152,950'));
  const bomDownload=page.waitForEvent('download');await page.locator('#export-bom').click();
  assert.ok((await readFile(await (await bomDownload).path(),'utf8')).includes('219650'));
  const planDownload=page.waitForEvent('download');await page.locator('#export-plan').click();
  const plan=JSON.parse(await readFile(await (await planDownload).path(),'utf8'));
  assert.equal(plan.plan.latencyMs,800);assert.equal(plan.plan.directSpinRequired,true);
  assert.equal(plan.budget.totalLow,152950);
  await page.locator('.panel-scroll').evaluate(el=>el.scrollTop=0);
  await page.screenshot({path:'artifacts/v3-plan.png'});
  await page.locator('[data-stage="full"]').click();
  await page.locator('#clearance').click();assert.equal(await page.locator('#clearance').getAttribute('aria-pressed'),'true');
  await page.locator('[data-panel="nodes"]').click();await page.locator('[data-node="cam-c"]').click();
  assert.ok((await page.locator('#detail').textContent()).includes('三壘側看台'));
  assert.ok((await page.locator('#detail').textContent()).includes('x -32'));
  await page.screenshot({path:'artifacts/perimeter-mounts.png'});
  await page.locator('[data-panel="dashboard"]').click();await page.locator('#clearance').click();
  await page.screenshot({path:'artifacts/stadium.png'});
  await page.locator('[data-view="plate"]').click();await page.screenshot({path:'artifacts/plate.png'});
  const beforeMetrics=await page.locator('#pitch-metrics').textContent();
  await page.locator('#ghost-actors').click();assert.equal(await page.locator('#ghost-actors').getAttribute('aria-pressed'),'true');
  assert.equal(await page.locator('#scene').getAttribute('data-pitcher-opacity'),'0.25');assert.equal(await page.locator('#scene').getAttribute('data-catcher-opacity'),'0.25');
  await page.screenshot({path:'artifacts/plate-ghost.png'});
  await page.locator('#actor-filter-options summary').click();await page.locator('#fade-pitcher').uncheck();
  assert.equal(await page.locator('#scene').getAttribute('data-pitcher-opacity'),'1');assert.equal(await page.locator('#scene').getAttribute('data-catcher-opacity'),'0.25');
  assert.equal(await page.locator('#ghost-actors').getAttribute('aria-pressed'),'mixed');
  await page.locator('#actor-opacity').fill('40');assert.equal(await page.locator('#scene').getAttribute('data-catcher-opacity'),'0.4');
  await page.locator('#actor-filter-options summary').click();
  await page.locator('#ghost-actors').click();assert.equal(await page.locator('#scene').getAttribute('data-pitcher-opacity'),'0.4');
  assert.equal(await page.locator('#pitch-metrics').textContent(),beforeMetrics);
  for(const stage of ['poc','bullpen','pilot','full']){
    await page.locator(`[data-stage="${stage}"]`).click();
    assert.ok(await page.locator('#node-list .node').count()>=5);
    assert.equal(await page.locator('#scene').getAttribute('data-catcher-opacity'),'0.4');
    if(stage==='poc'){
      await page.locator('[data-site="lab"]').click();await page.locator('[data-scene="near"]').click();
      await page.screenshot({path:'artifacts/lab.png'});
    }
  }
  await page.locator('#ghost-actors').click();assert.equal(await page.locator('#scene').getAttribute('data-pitcher-opacity'),'1');assert.equal(await page.locator('#scene').getAttribute('data-catcher-opacity'),'1');
  await page.locator('#light').click();await page.locator('#coverage').click();
  await page.screenshot({path:'artifacts/night.png'});
  await page.locator('#light').click();await page.locator('#coverage').click();
  for(const [scenario,expected] of [['ball','示範壞球'],['edge','待覆核'],['occluded','待覆核'],['strike','示範好球']]){
    await page.locator('#scenario').selectOption(scenario);assert.ok((await page.locator('#decision').textContent()).includes(expected));
  }
  await page.locator('#height').fill('195');await page.locator('#height').blur();
  assert.ok((await page.locator('#zone-meta').textContent()).includes('195'));
  await page.locator('[data-pitch="SL"]').click();await page.locator('#play').click();
  await page.waitForFunction(()=>!document.querySelector('#play').disabled);
  assert.ok((await page.locator('#record-count').textContent()).includes('1 球'));
  const jsonDownload=page.waitForEvent('download');await page.locator('#export-json').click();
  const jsonFile=await jsonDownload,records=JSON.parse(await readFile(await jsonFile.path(),'utf8')).records;
  assert.equal(records[0].pitch_type.label,'SL');assert.equal(records[0].source,'synthetic');assert.equal(records[0].trajectory.samples.length,241);
  assert.equal(records[0].measurements.spin_axis_world,null);assert.equal(records[0].measurements.spin_rpm,null);
  assert.equal(records[0].synthetic_spin.measurement,false);assert.equal(records[0].measurement_requirements.sample_to_visible_deadline_ms,800);
  const csvDownload=page.waitForEvent('download');await page.locator('#export-csv').click();const csv=await csvDownload;
  assert.ok((await readFile(await csv.path(),'utf8')).includes('user-selected-demo'));
  await page.reload();await page.waitForSelector('#record-count');assert.ok((await page.locator('#record-count').textContent()).includes('1 球'));
  await page.locator('[data-panel="metrics"]').click();assert.equal(await page.locator('.capability').count(),10);
  await page.locator('.capability summary').first().click();
  await page.locator('[data-panel="nodes"]').click();await page.locator('[data-node="r24"]').click();
  assert.ok((await page.locator('#detail').textContent()).includes('I/Q'));
  await page.locator('[data-panel="flow"]').click();assert.equal(await page.locator('#flow-panel [data-version-content="build"] .flow-list>div').count(),5);
  assert.equal(await page.locator('.latency-list>div').count(),8);
  assert.ok((await page.locator('#flow-panel').textContent()).includes('最早納入'));
  await page.screenshot({path:'artifacts/v3-flow.png'});
  await page.locator('[data-panel="dashboard"]').click();
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/mobile.png',fullPage:true});
  await page.locator('#ghost-actors').click();assert.equal(await page.locator('#scene').getAttribute('data-catcher-opacity'),'0.25');
  await page.locator('#actor-filter-options summary').click();await page.screenshot({path:'artifacts/mobile-filters.png'});
  const filterBox=await page.locator('.actor-filter-body').boundingBox();assert.ok(filterBox.x>=0&&filterBox.x+filterBox.width<=390,'mobile filter controls must not be clipped');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.locator('#actor-filter-options summary').click();
  for(const panel of ['nodes','spin','plan','flow','metrics']){
    await page.locator(`[data-panel="${panel}"]`).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`mobile overflow on ${panel}`);
  }
  await page.locator('[data-stage="poc"]').click();await page.locator('[data-panel="spin"]').click();
  await page.screenshot({path:'artifacts/v3-mobile-spin.png',fullPage:true});
  await page.setViewportSize({width:1512,height:1000});
  await page.locator('button[data-variant="buy"]').click();
  assert.equal(await page.locator('.app').getAttribute('data-variant'),'buy');
  assert.equal(await page.locator('#node-list .node').count(),2);
  assert.equal(await page.locator('#measurement-zone').isDisabled(),true);
  assert.equal(await page.locator('#option-fpga').isVisible(),false);
  assert.ok((await page.locator('#stage-brief').textContent()).includes('待報價'));
  await page.locator('[data-panel="plan"]').click();
  assert.equal(await page.locator('.purchase-card').count(),5);
  assert.ok((await page.locator('[data-product="b1"] .purchase-total').textContent()).includes('待報價'));
  assert.ok((await page.locator('[data-product="pro2-pitch"] .purchase-total').textContent()).includes('199,200'));
  assert.ok((await page.locator('[data-product="x3b"] .purchase-total').textContent()).includes('604,864'));
  await page.screenshot({path:'artifacts/v31-buy-plan.png'});
  const buyCSV=page.waitForEvent('download');await page.locator('#export-buy-csv').click();
  assert.ok((await readFile(await (await buyCSV).path(),'utf8')).includes('待報價'));
  const buyJSON=page.waitForEvent('download');await page.locator('#export-buy-plan').click();
  const buy=JSON.parse(await readFile(await (await buyJSON).path(),'utf8'));
  assert.equal(buy.solution_variant,'buy');assert.equal(buy.allRequirementsVerified,false);
  assert.equal(buy.products[0].estimate.firstYearLow,null);
  await page.locator('[data-panel="flow"]').click();
  assert.ok((await page.locator('#flow-panel [data-version-content="buy"]').textContent()).includes('iPad結果可用後約3秒'));
  assert.equal(await page.locator('#flow-panel .latency-list').isVisible(),false);
  for(const stage of ['poc','bullpen','pilot','full']){
    await page.locator(`[data-stage="${stage}"]`).click();
    assert.equal(await page.locator('#node-list .node').count(),2);
    assert.ok((await page.locator('#stage-brief').textContent()).includes('B成品'));
  }
  await page.locator('[data-stage="poc"]').click();
  await page.locator('[data-panel="dashboard"]').click();await page.locator('#play').click();
  await page.waitForFunction(()=>!document.querySelector('#play').disabled);
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('fieldlab-demo-v2')));
  assert.equal(stored.at(-1).solution_variant,'buy');assert.equal(stored.at(-1).source,'synthetic');
  await page.reload();await page.waitForSelector('#node-list .node',{state:'attached'});
  assert.equal(await page.locator('.app').getAttribute('data-variant'),'buy');
  await page.locator('[data-panel="nodes"]').click();
  await page.screenshot({path:'artifacts/v31-buy-nodes.png'});
  await page.setViewportSize({width:390,height:844});
  for(const panel of ['nodes','spin','plan','flow','metrics','dashboard']){
    await page.locator(`[data-panel="${panel}"]`).click();
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`buy mobile overflow on ${panel}`);
  }
  await page.locator('[data-panel="plan"]').click();
  await page.screenshot({path:'artifacts/v31-buy-mobile.png',fullPage:true});
  await page.locator('button[data-variant="build"]').click();
  assert.equal(await page.locator('#node-list .node').count(),9);
  assert.equal(await page.locator('#measurement-zone').isDisabled(),false);
  await page.goto(url.split('#')[0]+'#buy/poc/flow');
  await page.waitForFunction(()=>document.querySelector('.app')?.dataset.variant==='buy');
  assert.equal(await page.locator('#tab-flow').getAttribute('aria-selected'),'true');
  await page.goto(url.split('#')[0]+'#poc/plan');
  await page.waitForFunction(()=>document.querySelector('.app')?.dataset.variant==='build');
  assert.equal(await page.locator('#tab-plan').getAttribute('aria-selected'),'true');
  assert.deepEqual(errors,[]);
  console.log(JSON.stringify({passed:true,url,planVersion:'3.1',scenarios:4,stages:4,panels:6,variants:2,downloads:['pitch JSON','pitch CSV','BOM CSV','plan JSON','buy comparison CSV','buy plan JSON'],browserErrors:errors,mobileOverflow:false}));
} finally {await browser.close()}
