// 90-metric dictionary (v4.2 report pp.79–97). Engineering definition proposals, not CPBL/MLB private models.
// Every measured_value is null: writing a formula here does not mean the algorithm or data exists.
const PITCH_SCOPE='一期量測目標，尚待實球驗證',EXT_SCOPE='擴充與事件研究規格，不代表一期硬體已能提供全部資料';
export const metricCategories = {
  pitching:{name:'投球／截圖',scope:PITCH_SCOPE,phase:'P1'},
  batting:{name:'打擊／CPBL',scope:EXT_SCOPE,phase:'F1'},
  discipline:{name:'打席／選球／CPBL',scope:EXT_SCOPE,phase:'F1＋事件'},
  fielding:{name:'守備研究',scope:EXT_SCOPE,phase:'F2'},
};
// [name, id, unit, formula, required data, needs definition confirmation?]
const rows = {
  pitching:[
    ['釋球球速','release_speed','km/h','3.6 * norm(V_release)','3D release velocity'],
    ['進壘球速','plate_speed','km/h','3.6 * norm(V_at_rule_plane)','3D velocity + rule plane'],
    ['直接轉速','spin_rpm','rpm','60 * norm(omega) / (2*pi)','direct ball-surface orientations + timestamps'],
    ['三維有向轉軸','spin_axis','unit vector','omega / norm(omega); zero/ambiguous -> null','direct omega in declared world frame'],
    ['旋轉方向／clock tilt','spin_tilt','deg/clock','atan2(axis projection components); observer/zero convention required','signed axis + vendor projection profile',true],
    ['陀螺角','gyro','deg','asin(abs(dot(axis, unit(V)))) * 180/pi','direct axis + ball velocity'],
    ['幾何旋轉效率','spin_eff','ratio','norm(omega - dot(omega,vhat)*vhat) / norm(omega)','omega + V'],
    ['幾何有效轉速／true spin 對照','active_spin','rpm','spin_rpm * spin_eff; vendor true-spin definition must match','direct omega + V',true],
    ['出手高度','release_height','m','P_release.z - ground_z_at_release','3D trajectory + release event'],
    ['出手側向','release_side','m','P_release.x relative to plate origin','3D trajectory + frame definition'],
    ['出手延伸','extension','m','18.4404 - P_release.y (this field profile)','3D release position + rubber survey'],
    ['進壘點','plate_point','m','solve y(t)=rule_plane_y; return [x(t),z(t)]','trajectory + rule profile'],
    ['垂直出手角','release_vangle','deg','atan2(Vz, hypot(Vx,Vy))*180/pi','V_release'],
    ['水平出手角','release_hangle','deg','atan2(Vx,-Vy)*180/pi (pitch travels toward catcher)','V_release + sign convention'],
    ['VAA 垂直進壘角','vaa','deg','atan2(Vz,hypot(Vx,Vy))*180/pi at plate','V_plate'],
    ['HAA 水平進壘角','haa','deg','atan2(Vx,-Vy)*180/pi at plate','V_plate'],
    ['水平位移／Break','horizontal_break','m','x_measured(plane) - x_reference(plane)','trajectory + explicit reference model',true],
    ['誘導垂直位移 IVB','ivb','m','z_measured(plane) - z_no_lift(plane)','trajectory + gravity/drag/reference profile',true],
    ['總垂直位移','vertical_break','m','z_measured(plane) - z_linear_reference(plane)','trajectory + specified linear reference',true],
    ['球種','pitch_type','category','manual label OR trained classifier; unknown allowed','speed/axis/movement + labelled sessions'],
  ],
  batting:[
    ['擊球初速 EV','exit_velocity','km/h','3.6 * norm(V_just_after_contact)','post-contact 3D ball velocity'],
    ['擊球仰角 LA','launch_angle','deg','atan2(Vz,hypot(Vx,Vy))*180/pi','post-contact ball velocity'],
    ['擊球方向角','spray_angle','deg','atan2(Vx,Vy)*180/pi (outfield +y)','post-contact velocity + handedness'],
    ['擊球事件 BBE','bbe','count','count eligible contact events in declared BBE policy','contact/fair/foul/HR labels',true],
    ['滾地球 GB%','gb_pct','ratio','N_GB / N_eligible_BBE','batted-ball type + BBE eligibility'],
    ['非滾地球 Air%','air_pct','ratio','N_Air / N_eligible_BBE; =1-GB% only if complete partition','GB/Air and unknown type labels'],
    ['飛球 FB%','fb_pct','ratio','N_FB / N_eligible_BBE','versioned FB/IFFB classification'],
    ['平飛球 LD%','ld_pct','ratio','N_LD / N_eligible_BBE','versioned batted-ball classification'],
    ['內野飛球 IFFB%','iffb_pct','ratio','N_IFFB / N_eligible_BBE for selected CPBL profile; confirm','IFFB vs FB overlap policy',true],
    ['FB/LD%','fb_ld','ratio','CPBL text suggests N_FB/N_LD; do not treat as (FB+LD)/BBE','league clarification required',true],
    ['拉打 Pull%','pull_pct','ratio','N_pull / N_direction_valid_BBE','spray angle + batter handedness + sector rule'],
    ['中間方向 Center%','center_pct','ratio','N_center / N_direction_valid_BBE','spray angle + sector rule'],
    ['反方向 Oppo%','oppo_pct','ratio','N_oppo / N_direction_valid_BBE','spray angle + handedness + sector rule'],
    ['拉打滾地球%','pull_gb','ratio','N_(pull AND GB) / N_GB_direction_valid','direction + batted-ball type'],
    ['中間滾地球%','center_gb','ratio','N_(center AND GB) / N_GB_direction_valid','direction + batted-ball type'],
    ['反方向滾地球%','oppo_gb','ratio','N_(oppo AND GB) / N_GB_direction_valid','direction + batted-ball type'],
    ['拉打非滾地球%','pull_air','ratio','N_(pull AND Air) / N_Air_direction_valid','direction + batted-ball type'],
    ['中間非滾地球%','center_air','ratio','N_(center AND Air) / N_Air_direction_valid','direction + batted-ball type'],
    ['反方向非滾地球%','oppo_air','ratio','N_(oppo AND Air) / N_Air_direction_valid','direction + batted-ball type'],
    ['甜蜜點擊球率','sweet_spot','ratio','N_(8 <= LA <= 32 degrees) / N_angle_valid_BBE','ball LA + eligibility'],
    ['最大擊球初速','max_ev','km/h','max(EV_i), with valid measured values only','EV list'],
    ['平均擊球初速','avg_ev','km/h','sum(EV_i) / N_valid','EV list'],
    ['前50%平均擊球初速','top50_ev','km/h','mean(largest ceil(0.50*N) EV); rounding rule versioned','sorted valid EV list',true],
    ['前10%平均擊球初速','top10_ev','km/h','mean(largest ceil(0.10*N) EV); not a percentile cutoff','sorted valid EV list',true],
    ['最遠擊球距離','max_distance','m','max(observed or explicitly projected carry); never mix methods','landing point + origin + method'],
    ['全壘打平均距離','hr_distance','m','mean(distance_i for HR with consistent method)','HR event + observed/projected distance'],
    ['強擊球數','hard_hit','count','count(EV meets versioned 95mph threshold rule)','EV + >= or > rule + eligibility',true],
    ['強擊球率','hard_hit_pct','ratio','N_HH / N_eligible_BBE','hard-hit predicate + BBE policy'],
    ['Barrel 數','barrel','count','count(BARREL_v(EV_mph,LA_deg)); use complete lookup/predicate','EV + LA + full rule version',true],
    ['Barrel 率','barrel_pct','ratio','N_barrel / N_eligible_BBE','barrel predicate + eligibility',true],
    ['Barrel／PA','barrel_pa','ratio','N_barrel / N_PA','barrel events + plate appearances',true],
    ['Barrel／BIP','barrel_bip','ratio','N_(barrel AND eligible_BIP) / N_BIP','barrel + BIP/HR eligibility',true],
    ['Barrel／揮棒','barrel_swing','ratio','N_barrel / N_swings','barrel events + swings',true],
    ['Barrel／投球','barrel_pitch','ratio','N_barrel / N_pitches','barrel events + pitches',true],
    ['強擊球／BIP','hh_bip','ratio','N_(HH AND eligible_BIP) / N_BIP','hard-hit + BIP/HR policy'],
    ['強擊球／揮棒','hh_swing','ratio','N_HH / N_swings','hard-hit events + swings'],
    ['強擊球／投球','hh_pitch','ratio','N_HH / N_pitches','hard-hit events + pitches'],
  ],
  discipline:[
    ['打擊率 AVG','avg','ratio','H / AB','official scoring: H, AB'],
    ['長打率 SLG','slg','ratio','(1B + 2*2B + 3*3B + 4*HR) / AB','official hit types + AB'],
    ['純長打率 ISO','iso','ratio','SLG - AVG','SLG + AVG, same sample'],
    ['上壘率 OBP','obp','ratio','(H+BB+HBP) / (AB+BB+HBP+SF), standard profile','official scoring; CPBL article denominator must confirm',true],
    ['wOBA','woba','ratio','(wBB*BB_eligible + wHBP*HBP + w1*1B + w2*2B + w3*3B + wHR*HR) / D_v','year/league weights + eligible denominator',true],
    ['三振率 K%','k_pct','ratio','K / PA','strikeout + PA events'],
    ['保送率 BB%','bb_pct','ratio','BB / PA; IBB policy versioned','walk + PA events'],
    ['揮空率 Whiff%','whiff','ratio','N_miss / N_swings','swing + contact labels'],
    ['追打率 Chase%','chase','ratio','N_(swing AND outside_zone) / N_outside_zone','pitch position + zone + swing'],
    ['好球帶進壘率 Zone%','zone_pct','ratio','N_in_zone / N_location_valid_pitches','pitch + location validity + zone profile'],
    ['好球帶揮棒率','zone_swing','ratio','N_(swing AND in_zone) / N_in_zone','swing + in-zone'],
    ['好球帶接觸率','zone_contact','ratio','N_(contact AND in_zone) / N_(swing AND in_zone)','swing + contact + in-zone'],
    ['追打區進壘率','chase_zone','ratio','N_in_chase_region / N_location_valid_pitches','explicit chase-region geometry; not all outside-zone',true],
    ['追打接觸率','chase_contact','ratio','N_(contact AND outside_zone) / N_(swing AND outside_zone)','contact + swing + outside; CPBL region convention confirm',true],
    ['邊界區進壘率 Shadow%','shadow_zone','ratio','N_in_shadow_region / N_location_valid_pitches','versioned shadow geometry',true],
    ['首球揮棒率','first_swing','ratio','N_(swing AND first_pitch_of_PA) / N_first_pitch_of_PA','PA IDs + pitch order + swing'],
    ['揮棒率 Swing%','swing','ratio','N_swings / N_pitches','swing + pitch events'],
    ['中心區進壘率 Heart%','heart','ratio','N_in_heart / N_location_valid_pitches','versioned heart geometry',true],
    ['中心區揮棒率','heart_swing','ratio','N_(swing AND heart) / N_heart','swing + heart region',true],
    ['兩好球後三振率','two_strike_k','ratio','K / N_PA_that_reached_two_strikes; confirm league definition','count transitions + PA outcomes',true],
    ['BABIP','babip','ratio','(H - HR) / (AB - K - HR + SF)','official H, HR, AB, K, SF'],
    ['接觸打擊率','contact_avg','ratio','H / (AB - K), following requested contact convention','H, AB, K'],
    ['接觸 wOBA','contact_woba','ratio','weighted_hits / D_contact_v; proposed AB-K+SF, unresolved','weights + scoring; CPBL printed denominator conflicts',true],
  ],
  fielding:[
    ['守備反應時間','reaction','s','t_first_sustained_move - t_contact','player tracks + contact + motion threshold'],
    ['守備路徑效率','route','ratio','straight_distance_to_fielding_point / travelled_distance','player trajectory + start/end event'],
    ['守備跑速','run_speed','m/s','norm(dP_player/dt) with versioned smoothing window','calibrated timed player positions'],
    ['傳球球速','throw_speed','km/h','3.6 * norm(V_throw_release)','ball trajectory + release event'],
    ['接傳交換時間','transfer','s','t_throw_release - t_secure_catch','catch + throw event labels'],
    ['捕手 Pop Time','pop_time','s','t_receiver_catch - t_catcher_secure_catch','two catch events + common clock'],
    ['接殺機率 p_i','catch_prob','probability','calibrated model P(out | pre-outcome opportunity features)','start pos + ball path + hang time + context'],
    ['OAA-like（非官方 OAA）','oaa_like','outs','sum_i(y_i - p_i), one assigned opportunity per eligible play','outcome + held-out calibrated probabilities'],
    ['成功率高於預期','success_added','ratio','mean(y_i) - mean(p_i), with sample count and interval','eligible opportunities + probabilities'],
    ['守備得分價值研究','runs_saved','runs','sum(outcome_value - expected_value), own run model','state/run-expectancy model + outcomes'],
  ],
};
export const metricsCatalog = Object.entries(rows).flatMap(([category,list])=>list.map(([name,id,unit,formula,required,confirm=false])=>({
  id,name,category,unit,formula,required,phase:metricCategories[category].phase,scope:metricCategories[category].scope,
  status:'planned',needs_definition_confirmation:confirm,measured_value:null,sample_count:0,value_origin:null})));

// Ambiguities that must not be silently resolved (p.97).
export const definitionAmbiguities = [
  ['LA','文章文字可能把球的仰角與球棒角度混在一起','LA 用擊球後球速向量；attack angle 另欄，需球棒追蹤。'],
  ['Top50／Top10','前段平均與中位數／百分位數不同','取排序後前 k 個平均；k 的取整方式版本化。'],
  ['FB/LD%／IFFB%','分母、重疊分類與符號可能不一致','保留待確認 flag，不把別家定義無聲套入。'],
  ['OBP／contact wOBA','文字與列式對 SF、K 等排除不一致','標準 OBP 與 CPBL 待確認版分 profile；contact wOBA 未定不輸出正式值。'],
  ['Hard-hit／Barrel','門檻 >／≥、mph／km/h 與完整桶狀區域','Hard-hit 邊界版本化；Barrel 必需完整 EV-LA predicate。'],
  ['wOBA 年度權重','2025 權重不能永久套用','weights_id 含 league／season，IBB、SF、HBP 分母規則也存。'],
  ['Heart／Shadow／Chase','區域不是從名詞就有唯一幾何','先取得完整多邊形／正規化邊界，否則只展示 planned。'],
];
// Ratios keep 0–1 in data; zero denominators are unknown, never 0%.
export const ratio=(numerator,denominator)=>Number.isFinite(numerator)&&Number.isFinite(denominator)&&denominator>0?numerator/denominator:null;
export function searchMetrics(query='',category='all'){
  const q=query.trim().toLowerCase();
  return metricsCatalog.filter(m=>(category==='all'||m.category===category)&&(!q||[m.id,m.name,m.formula,m.required,m.unit].some(s=>s.toLowerCase().includes(q))));
}
