import { PLAN, sources, fmtMoney } from './plan.js';
import { priceAudit, purchaseProducts, purchaseEstimate, purchaseAssumptions } from './procurement.js';
const link=id=>`<a href="${sources[id].url}" target="_blank" rel="noopener">${sources[id].title} ↗</a>`;
const range=(a,b)=>a===null?'待報價':`${fmtMoney(a)}–${fmtMoney(b)}`;

export function auditHTML(){return `<div class="audit-box"><span class="eyebrow">PRICE AUDIT / ${PLAN.priceChecked}</span><h3>加總正確 ≠ 整套可採購且達標</h3><p>133,000–191,000 × 1.15 = 152,950–219,650。保留原BOM金額，但改明示為工程預留；47萬是累計額度，100萬是預算上限，不是廠商報價。</p></div>
  <details class="plan-detail" open><summary>三項有價格來源，其餘為工程預留</summary><table class="plan-table"><thead><tr><th>裸機 / 公開單價</th><th>證據與限制</th></tr></thead><tbody>${priceAudit.map(p=>`<tr><td>${p.model}<small>USD ${p.usd} ≈ ${fmtMoney(p.usd*PLAN.fxUsdTwd)} / 台（×32假設）</small></td><td>${p.status}</td></tr>`).join('')}</tbody></table><div class="reference-links">${priceAudit.map(p=>link(p.source)).join('')}</div><p>公開裸機價不含鏡頭、線材及運保稅費；BOM單價15–21k等已是較高的台幣工程預留，不能再把裸機價加一次。</p><p>鏡頭、照明、同步、防護、儲存、治具及電源尚未取得逐項書面報價。實際含稅/運費/保固與可借資源需逐筆替換，不能把15%風險預留當成精度保證。</p></details>
  <div class="disclaimer">A版「自研」是購買可取得raw的工業感測器，自研演算法/資料管線/加速；不是15–22萬就能自製雷達RF PCB、ASIC及量產整機。自製板、NRE、人力、EMC/RF驗證與高規旋轉光學升級另案。</div>`;}

export function buyPlanHTML(){return `
  <span class="eyebrow">B / BUY & INTEGRATE / ${PLAN.priceChecked}</span><h2>購買成品，自研應用</h2>
  <p class="lead">買廠商量測引擎，用授權資料做adapter、分析、Dashboard與孿生。這與A版取得原始影像/IQ自行解算，是兩種不同交付範圍。</p>
  <div class="buy-critical"><b>目前沒有一款可直接標成全部符合</b><p>raw L0/L1、普通球直接有向三維軸、場內淨空、取樣到自製畫面800ms，需要分別取得證據。原廠App看得到數字，不代表我們能即時取得。</p></div>
  <div class="budget-hero"><small>場邊整機候選：TrackMan B1</small><strong>待正式報價</strong><span>硬體＋Data Access Package / API＋軟體訂閱＋部署配件。未知項目不是零元，不能先宣稱47萬或100萬內一定完成。</span></div>
  <details class="plan-detail" open><summary>兩版的工作邊界</summary><table class="plan-table"><thead><tr><th>項目</th><th>A 自研</th><th>B 成品應用</th></tr></thead><tbody><tr><td>自己做</td><td>raw擷取、同步、球縫姿態、融合、算法、孿生</td><td>授權adapter、座標/單位、事件、分析、孿生</td></tr><tr><td>硬體</td><td>開放相機/雷達＋鏡頭/照明/同步</td><td>整機＋相容主機＋授權/配件</td></tr><tr><td>核心限制</td><td>直接旋轉難度與實拍未過關</td><td>raw、API權利、延遲、黑盒方法</td></tr><tr><td>一期直接旋轉</td><td>自己實作並盲測</td><td>要求廠商方法/欄位/精度證據再驗收</td></tr></tbody></table></details>
  <h3>現成產品價目與限制</h3><p class="mini-note">查核日${PLAN.priceChecked}，不是型號發布年。以下美國公開價格不能代替台灣職業球團的正式報價；職業隊適用資格、地區販售及出口/保固須確認。</p>
  <div class="purchase-products">${purchaseProducts.map(p=>{const e=purchaseEstimate(p);return `<article class="purchase-card" data-product="${p.id}"><h3>${p.name}</h3><div class="purchase-status">${p.status}</div><div class="purchase-price">${p.hardwareUsd===null?'硬體：需詢價':`硬體參考 USD ${p.hardwareUsd.toLocaleString('en-US')} · ${fmtMoney(e.hardwareTwd)}（×32）`}</div><p>${p.annualUsd===null?'軟體訂閱頁列USD 2,500/期（約8萬）；期間、地區與合約條件待確認，不擅自當成年費。API費未公開。':`本表訂閱基準 USD ${p.annualUsd.toLocaleString('en-US')}/年 ≈ ${fmtMoney(e.annualTwd)}/年；適用方案需確認。`}</p><div class="purchase-total"><small>首年已知基礎成本估算 · 非完整交付價</small><strong>${range(e.firstYearLow,e.firstYearHigh)}</strong><small>三年已知基礎成本估算</small><b>${range(e.threeYearLow,e.threeYearHigh)}</b></div><p>${p.accessories}。</p><details><summary>原始介面、直接旋轉、安裝與延遲</summary><p><b>資料：</b>${p.data}</p><p><b>旋轉：</b>${p.spin}</p><p><b>場地：</b>${p.placement}</p><p><b>延遲：</b>${p.latency}</p></details><div class="reference-links">${[...new Set([p.source,p.feeSource,...p.sources])].map(link).join('')}</div></article>`;}).join('')}</div>
  <details class="plan-detail" open><summary>每個金額怎麼算？</summary><p>${purchaseAssumptions.note}</p><div class="formula-card">首年已知基礎 = 硬體USD × 32 × (1.10～1.20)<br>＋部署配件預留＋一年的公開訂閱基準<br>三年已知基礎 = 首年已知基礎＋2 × 年度訂閱基準</div><p>未加入尚無報價的API/CSV升級授權、自研應用NRE、廠商支援、維修與永久工程。這些「已知基礎」不是完整TCO；會員稅費/匯差亦需正式報價補足。X3B套裝的PC與腳架不重複計價，PRO 2.0投打雙功能也不重複加1,000美元升級費。</p></details>
  <details class="plan-detail"><summary>維護與人力要另算，不當成免費</summary><p>A版可先編每年實際硬體採購額3–5%作備品準備金，加校正材料/治具5–15k；B版另加必要訂閱及廠商維修/RMA運費。以上為內部預算假設，不是廠商服務合約，實際人力與重大故障另計。</p><p>完整TCO = 硬體到岸＋安裝＋NRE＋各年(必要授權/API＋儲存/網路＋維護/校正)。NRE = 各角色人月×全成本月薪＋測試/認證費；本次硬體比較未把人力算成零價交付。</p></details>
  <h3>現階段建議順序</h3><div class="gate-list"><article><span>01 / 先盤點</span><b>球團現有B1 / Rapsodo / X3B與合約</b><p>索取型號、序號、版本、可匯出樣本、API權限與借測時段，不先花錢重買。</p></article><article><span>02 / 先驗介面</span><b>授權到位後，2–6週做應用原型</b><p>先重播合法匯出檔，再做正式adapter；不將CSV批次或雲端feed說成本地raw即時通道。</p></article><article><span>03 / A+B平行</span><b>成品供訓練/對照，A版做自有量測</b><p>共享孿生與事件schema，但分開source、method、時間與成本。參考儀有自己的誤差，不能直接當絕對真值。</p></article></div>
  <div class="export-row"><button id="export-buy-csv">下載成品比較 CSV</button><button id="export-buy-plan">下載 B版計畫 JSON</button></div>
  <p class="mini-note">未聯繫廠商、未下單。高爾夫Mevo+／R10／Uneekor等不列為已驗證棒球直接旋轉解決方案。</p>`;}

export function buySpinHTML(){return `<span class="eyebrow">B / VENDOR MEASUREMENT REVIEW</span><h2>買到轉速 ≠ 拿到直接三維軸</h2><div class="requirement-card"><small>兩版共同硬需求，B版未豁免</small><strong>第一期直接rpm＋三維有向軸</strong><p>普通未標記球、來源方法清楚、誤差/有效率盲測；沒有證據不能標已滿足。</p></div><p class="lead">畫面仍只有合成轉軸。成品內部鏡頭與曝光不可當成A版的可調相機，因此本版不顯示A版光學試算器。</p><div class="buy-critical"><b>實測轉速 / 三維軸：— / —</b><p>尚無成品連線與授權資料。將原廠有向軸轉成統一座標前，先確認右手定則、座標軸、角度單位、gyro正負及版本。</p></div><div class="gate-list"><article><span>METHOD</span><b>分清直接觀測與球路推估</b><p>vendor提供的spin direction / tilt / movement-derived axis不可不經查核就映射成direct_spin_axis。只給二維角度時，不補造第三維。</p></article><article><span>CONTRACT</span><b>索取真實逐球範例與方法說明</b><p>rpm、3D axis或完整角度定義、method、validity、誤差、取樣支持窗、資料產生/發布時刻；缺欄保留null。</p></article><article><span>ACCEPTANCE</span><b>先完成普通球獨立盲測</b><p>即使App顯示數字，也要測有向軸反向錯誤、倍頻、遮擋與逾時。借用另一成品不自動變成無誤差真值。</p></article></div><div class="reference-links">${link('b1Specs')}${link('b1Live')}${link('pro3')}${link('x3b')}</div>`;}

export function buyFlowHTML(){return `<span class="eyebrow">B / LICENSED DATA PIPELINE</span><h2>成品介接，延遲另驗</h2><div class="buy-critical"><b>0.8秒仍是需求，不是成品已具備能力</b><p>B1官方公開Live Feed是「iPad結果可用後約3秒內」的目標；起點不同，不能與800ms感測到畫面直接比較為達標。未證明能滿足，採購前需另談合法本地通道並實測。</p>${link('b1Live')}</div><div class="flow-list"><div><small>01 / VENDOR</small><strong>成品內部感測與解算</strong><p>相機/雷達內部信號不可見；自研FPGA放在API後面，不能倒推出未開放的raw或消除廠商端延遲。</p></div><div><small>02 / LICENSE</small><strong>原廠App → 授權feed / 匯出</strong><p>B1的Data Access Package另購；Rapsodo與X3B的CSV/Cloud也需逐項確認。網路與雲端時間都必須計入。</p></div><div><small>03 / ADAPTER</small><strong>HTTPS接收、驗證、去重與封存</strong><p>以vendor play/session id做idempotency；處理版本、遺漏與重排。B1文件指出訊息無重送緩衝，須缺漏監測並用事後資料對帳。</p></div><div><small>04 / NORMALIZE</small><strong>L2/L3結果統一格式</strong><p>保存原始vendor payload（非sensor raw），對照座標/單位/方法/品質；後端保管帳密。不得用接收時間取代曝光時間。</p></div><div><small>05 / DISPLAY</small><strong>WebSocket → 自研孿生 / Dashboard</strong><p>來源顯示vendor-derived；沒有axis或完整球路就留空或明標重建。GitHub只作展示，正式資料在授權後端。</p></div></div><div class="formula-card">總延遲 = 廠商觀測/解算 + App等待 + 傳輸<br>+ adapter / 儲存 + WebSocket + 實際顯示</div><p class="mini-note">B版未分配假的800ms預算，也不因選成品就豁免硬需求。若廠商不能滿足，B版僅作訓練應用/參考儀，A版繼續承擔自研目標。</p><div class="reference-links">${link('b1API')}${link('rapFAQ')}${link('x3b')}</div>`;}
